#!/bin/bash -x
#
#PBS -l select=1:ncpus=32:mem=40G:mpiprocs=1:ompthreads=32
#PBS -N dborisovMUZA
#PBS -l walltime=1:00:00
#PBS -o /RHM-Lustre3.2/users/muza-art/dborisov/copy_inmcm
#PBS -e /RHM-Lustre3.2/users/muza-art/dborisov/copy_inmcm
#PBS -j oe
#PBS -W umask=22

cd /RHM-Lustre3.2/users/muza-art/dborisov/copy_inmcm

#module use /RHM-Lustre3.2/users/kompa/msmirnov/software/modules
#module load ms.kkpa.oper

module use /RHM-Lustre3.2/users/cosmo/akirsanov/modules
module load ak.py3.10.4.20251031

module load alps
aprun -B -cc numa_node python3 extract.py
